apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: worker
      app: demo-voting-app
  template:
    metadata:
      name: worker-pod
      labels:
        tier: worker
        app: demo-voting-app

    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker