apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend-result
      app: demo-voting-app
  template:
    metadata:
      name: result-pod
      labels:
        tier: frontend-result
        app: demo-voting-app

    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
