apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend-vote
      app: demo-voting-app
  template:
    metadata:
      name: vote-pod
      labels:
        tier: frontend-vote
        app: demo-voting-app

    spec:
      containers:
        - name: vote
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
