apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
      app: demo-voting-app
  template:
    metadata:
      name: db-pod
      labels:
        tier: db
        app: demo-voting-app

    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
