apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    name: vote-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    tier: frontend-vote
    app: demo-voting-app
